=== TotoooDev/TotoooDev.github.io/XML/video_game.dtd
<!ENTITY % month
    "(1|2|3|4|5|6|7|8|9|10|11|12)">
<!ENTITY % day
	"(1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31)">  
<!ENTITY % year 
    "CDATA">

<!ENTITY % coreattrs
	 "id       ID      #IMPLIED
	  class    CDATA   #IMPLIED
	  title    CDATA   #IMPLIED">

<!ENTITY % inline "img | keyword | a | highlight">
<!ENTITY % datainline "(#PCDATA | %inline; )*">
<!ENTITY % datainlineul "(#PCDATA | p | %inline; | ul)*">

<!ELEMENT name
    (#PCDATA)>

<!ELEMENT date EMPTY>
<!ATTLIST date
    year %year; #REQUIRED
    month %month; #REQUIRED
    day %day; #REQUIRED
	%coreattrs; #IMPLIED
    >

<!ELEMENT studio
    (#PCDATA)>
<!ATTLIST studio
    %coreattrs; #IMPLIED
    >

<!ELEMENT editor
    (#PCDATA)>
<!ATTLIST editor
    %coreattrs; #IMPLIED
    >

<!ELEMENT genre
    (#PCDATA)>
<!ATTLIST genre
    %coreattrs; #IMPLIED
    >

<!ELEMENT numsold EMPTY>
<!ATTLIST numsold
    sold CDATA #REQUIRED
	%coreattrs; #IMPLIED
    >

<!ELEMENT award EMPTY>
<!ATTLIST award
    title CDATA #REQUIRED
    event CDATA #REQUIRED
	%coreattrs; #IMPLIED
		>

<!ELEMENT support EMPTY>
<!ATTLIST support
    name "(PC|Wii|PlayStation 3|Xbox 360|Nintendo Switch)" #REQUIRED
	%coreattrs; #IMPLIED
    >

<!ELEMENT info
    (name, date, studio, editor?, genre, numsold?, award*, support)>
<!ATTLIST info
    %coreattrs; #IMPLIED
    >

<!ELEMENT dlc
    (name, date, award*)>
<!ATTLIST dlc
    %coreattrs; #IMPLIED
    >

<!ELEMENT description
    %datainlineul;>
<!ATTLIST description
    %coreattrs; #IMPLIED
    >

<!ELEMENT story
		%datainlineul;>
<!ATTLIST story
		%coreattrs; #IMPLIED
		>

<!ELEMENT screenshots
    (img, p)>
<!ATTLIST screenshots
    %coreattrs; #IMPLIED
    >

<!ELEMENT videogame
    (info, dlc*, comment, description, story, screenshots)>
<!ATTLIST videogame
    %coreattrs; #IMPLIED
    >

<!ELEMENT img EMPTY>
<!ATTLIST img
		src         CDATA  #REQUIRED
		alt         CDATA  #REQUIRED
		longdesc    CDATA  #IMPLIED
		height      CDATA  #IMPLIED
		width       CDATA  #IMPLIED
		%coreattrs;
		>

<!ELEMENT a (#PCDATA)*>
<!ATTLIST a
		href        CDATA  #IMPLIED
		%coreattrs;
		>

<!ELEMENT highlight %datainline;>
<!ATTLIST highlight
		%coreattrs;
		>

<!ELEMENT p %datainline;>
<!ATTLIST p
		%coreattrs;
		>

<!ELEMENT ul (li)+>

<!ELEMENT li %datainlineul;>
<!ATTLIST li
		%coreattrs;
		>

<!-- certains éléments et entités ont été "empruntées" de l'exemple fourni sur updago :) -->

=== TotoooDev/TotoooDev.github.io/XML/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videogame SYSTEM "video_game.dtd">

<videogame>

    <info>
        <name> Portal 2 </name>

        <date day = "19" month = "4" year = "2011" />

        <studio> Valve </studio>

        <genre> Puzzle platformer </genre>

        <numsold sold = "4000000" />

        <award title = "Game of the Year" event = "IGN" />
        <award title = "Meilleur scenario, Meilleur design" event = "British Academy Video Games Awards" />
        
        <support name = "PC" />
        <support name = "PlayStation 3" />
        <support name = "Xbox 360" />
        <support name = "Nintendo Switch" />
    </info>

    <dlc>
        <name> Peer Review </name>

        <date day = "4" month = "10" year = "2011" />

        <award title = "Best DLC" event = "Golden Joystick Awards 2012" />
    </dlc>

    <description>
        <p>Portal 2 est un puzzle platformer développé et édité par Valve, qui a pour principale mécanique de gameplay le portal gun, un outil qui permet de poser des portails de téléportation sur des murs. Les portails sont connectés entre eux : lorsque le joueur rentre dans le portail orange, il ressort du portail bleu avec la même vitesse qu'il avait en rentrant. Le jeu possède plus d'une centaine de chambres de tests qui exploitent tous les mécaniques du jeu d'une manière différente (en comptant la co-op et les DLC).</p>
    </description>

    <story>
        <p>Le jeu se déroule plusieurs années après Portal, lorsque Chell, le personnage du joueur est réveillée de son sommeil cryogénique par Wheatley, un petit robot sphérique qui lui dicte la marche à suivre pour sortir du complexe dans lequel Chell était endormie. En voulant sortir, Wheatley réactive sans faire exprès GLaDoS, l'antagoniste principale du premier jeu. GLaDoS décide de placer Chell dans ses salles de test afin de tester son intelligence.</p>
    </story>

    <screenshots>
        <img src = "../../Images/portal2.png" alt = "portal 2 mais c'est moi qui ai dessiné" />
    </screenshots>

</videogame>
